apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: docker.gabrilov.com/mysql-webapp
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - volumeMounts:
          - name: registry-ca
            mountPath: /etc/docker/certs.d/docker.gabrilov.com
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: registry-ca
        secret:
          secretName: certificado-registro
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
