FROM python:bullseye
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
#Server will reload itself on file changes if in dev mode
ENV FLASK_ENV=development
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y python3-mysqldb && rm -rf /var/lib/apt/lists/*
COPY ./backend/ .
RUN pip3 install -r requirements.txt
COPY ./backend/ .
CMD ["flask", "run"]