apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: trastolillo/flask
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: password-mysql
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: host-mysql
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
  selector:
    app: flaskapi
  type: LoadBalancer